In [59]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

df=pd.read_csv("../data/data.csv")

pd.set_option("display.max_columns", None)
df.head()

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),Deaths in the last 3 years registered with the civil authority (%),Population living in households with electricity (%),Population living in households with an improved drinking-water source1 (%),Population living in households that use an improved sanitation facility2 (%),Households using clean fuel for cooking3 (%),Households using iodized salt (%),Households with any usual member covered under a health insurance/financing scheme (%),Children age 5 years who attended pre-primary school during the school year 2019-20 (%),Women (age 15-49) who are literate4 (%),Women (age 15-49) with 10 or more years of schooling (%),Women age 20-24 years married before age 18 years (%),Births in the 5 years preceding the survey that are third or higher order (%),Women age 15-19 years who were already mothers or pregnant at the time of the survey (%),Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any method6 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any modern method6 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Female sterilization (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Male sterilization (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - IUD/PPIUD (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Pill (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Condom (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Injectables (%),Total Unmet need for Family Planning (Currently Married Women Age 15-49 years)7 (%),Unmet need for spacing (Currently Married Women Age 15-49 years)7 (%),Health worker ever talked to female non-users about family planning (%),Current users ever told about side effects of current method of family planning8 (%),Mothers who had an antenatal check-up in the first trimester (for last birth in the 5 years before the survey) (%),Mothers who had at least 4 antenatal care visits (for last birth in the 5 years before the survey) (%),Mothers whose last birth was protected against neonatal tetanus (for last birth in the 5 years before the survey)9 (%),Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%),Mothers who consumed iron folic acid for 180 days or more when they were pregnant (for last birth in the 5 years before the survey} (%),Registered pregnancies for which the mother received a Mother and Child Protection (MCP) card (for last birth in the 5 years before the survey) (%),Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%),Average out-of-pocket expenditure per delivery in a public health facility (for last birth in the 5 years before the survey) (Rs.),Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%),Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%),Institutional births (in the 5 years before the survey) (%),Institutional births in public facility (in the 5 years before the survey) (%),Home births that were conducted by skilled health personnel (in the 5 years before the survey)10 (%),Births attended by skilled health personnel (in the 5 years before the survey)10 (%),Births delivered by caesarean section (in the 5 years before the survey) (%),Births in a private health facility that were delivered by caesarean section (in the 5 years before the survey) (%),Births in a public health facility that were delivered by caesarean section (in the 5 years before the survey) (%),Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%),Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%),Children age 12-23 months who have received BCG (%),Children age 12-23 months who have received 3 doses of polio vaccine13 (%),Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%),Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%),Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%),Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%),Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%),Children age 9-35 months who received a vitamin A dose in the last 6 months (%),Children age 12-23 months who received most of their vaccinations in a public health facility (%),Children age 12-23 months who received most of their vaccinations in a private health facility (%),Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%),Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%),Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%),Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%),Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%),Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%),Children under age 3 years breastfed within one hour of birth15 (%),Children under age 6 months exclusively breastfed16 (%),Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%),"Breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)","Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)","Total children age 6-23 months receiving an adequate diet16, 17 (%)",Children under 5 years who are stunted (height-for-age)18 (%),Children under 5 years who are wasted (weight-for-height)18 (%),Children under 5 years who are severely wasted (weight-for-height)19 (%),Children under 5 years who are underweight (weight-for-age)18 (%),Children under 5 years who are overweight (weight-for-height)20 (%),Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%),Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%),Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%),Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%),Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%),Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%),All women age 15-49 years who are anaemic22 (%),All women age 15-19 years who are anaemic22 (%),Women age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%),Men (age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%),Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%),Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,Nicobars,Andaman & Nicobar Islands,882,764,125,78.0,23.0,973,927,98.0,83.2,97.9,98.8,83.5,56.9,99.4,2.7,(29.5),87.5,53.5,11.4,0.0,1.8,100.0,65.3,57.2,46.4,0.0,2.7,2.0,4.9,1.2,9.5,3.3,40.4,49.4,62.8,71.7,78.0,72.6,43.9,97.9,85.1,2278,*,92.5,97.8,96.7,0.8,98.6,11.5,*,10.7,(64.2),(94.1),(80.4),(69.1),(71.9),(67.3),(20.7),(3.1),(68.6),94.9,(100.0),(0.0),5.7,*,*,*,1.8,(85.7),55.4,*,*,(19.4),*,(18.7),21.6,15.7,7.8,24.6,1.5,8.2,39.1,62.5,37.7,38.4,*,38.3,48.0,7.4,3.9,13.1,9.6,4.4,15.4,23.2,8.5,35.4,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5
1,North & Middle Andaman,Andaman & Nicobar Islands,874,789,108,82.7,19.8,950,844,100.0,(92.6),93.2,92.2,86.4,61.3,99.9,2.1,(30.1),84.0,41.0,15.4,1.5,3.8,100.0,84.1,73.1,48.3,0.6,6.4,7.8,9.3,0.0,5.8,1.3,23.2,83.2,74.5,79.2,91.1,83.7,24.1,99.2,92.5,1904,*,94.3,97.7,95.0,0.7,98.3,12.9,*,11.4,*,*,*,*,*,*,*,*,*,(89.6),*,*,4.5,*,*,*,7.0,*,27.3,*,*,(6.5),*,(5.9),27.0,27.0,8.3,42.8,0.8,8.6,35.9,79.3,30.4,62.5,*,62.1,47.8,7.2,6.4,16.7,9.1,6.9,18.3,18.4,4.0,27.4,22.6,6.0,32.2,1.7,0.3,15.8,46.8,70.5,5.1,45.3
2,South Andaman,Andaman & Nicobar Islands,868,844,134,84.7,21.0,967,935,96.5,92.2,99.6,97.9,89.3,91.9,99.7,1.2,(50.8),86.7,57.5,17.1,0.5,2.8,98.2,57.1,50.5,34.0,0.0,2.8,1.8,10.6,0.3,17.6,8.6,31.2,88.2,79.4,85.9,92.1,81.0,61.9,98.9,88.1,3460,*,89.8,99.5,83.8,0.0,96.9,37.1,(79.1),29.6,(76.3),(96.6),(100.0),(79.0),(94.8),(81.7),(33.7),(0.0),(85.3),84.0,(93.1),(4.3),6.0,*,*,*,0.0,(77.3),51.1,*,*,(22.3),*,23.5,21.1,12.6,3.5,17.4,7.2,10.0,39.0,78.2,43.4,57.6,*,57.7,43.2,7.5,9.5,18.4,9.3,7.8,18.1,12.7,4.9,23.0,17.9,6.1,26.9,1.3,0.7,8.0,19.6,50.8,1.7,32.8
3,Srikakulam,Andhra Pradesh,874,780,100,60.0,20.7,1140,1163,95.0,71.0,99.9,87.7,71.6,74.7,76.5,75.6,(0.0),64.3,42.5,25.4,0.0,5.5,78.0,72.3,72.2,71.0,0.3,0.6,0.0,0.3,0.0,5.7,3.6,16.0,45.8,79.7,78.4,94.4,67.5,35.3,100.0,90.8,3479,*,97.7,97.9,52.2,0.5,96.4,57.0,73.8,44.5,(82.8),(100.0),(93.3),(82.8),(89.7),(93.3),(34.9),(74.8),(89.7),69.6,(97.0),(3.0),11.9,*,*,*,1.3,(79.7),42.8,*,*,(14.0),*,16.1,19.7,19.5,7.4,21.4,4.5,13.8,27.2,54.0,59.6,62.8,*,62.6,59.2,8.2,7.8,17.4,6.8,8.6,17.6,12.8,5.9,22.1,14.4,5.5,22.9,1.0,0.2,3.8,7.1,21.3,0.6,28.3
4,Vizianagaram,Andhra Pradesh,902,853,134,56.0,20.6,1114,898,95.4,81.7,99.5,93.1,61.7,60.3,85.0,76.7,(25.2),58.3,37.6,33.7,2.2,12.7,72.5,71.2,71.2,69.3,1.3,0.0,0.0,0.6,0.0,6.7,4.7,21.1,36.4,76.1,71.4,91.3,59.6,32.4,98.8,83.9,1931,*,89.2,99.0,70.6,0.5,97.6,41.3,70.3,30.3,(76.8),*,(100.0),(76.8),(90.3),(92.5),(35.0),(77.3),(83.6),85.9,(100.0),(0.0),7.5,*,*,*,1.4,(83.5),55.6,*,*,(2.5),*,1.8,36.4,19.2,8.3,32.2,4.7,16.9,28.8,58.0,66.7,64.6,*,64.0,73.9,6.2,7.0,14.3,5.8,7.5,14.5,12.9,6.6,25.2,14.8,6.4,25.1,4.9,0.6,7.3,11.4,21.5,0.8,32.3

In [25]:
for i,column in enumerate(df.columns):
    print(i, column)

0 District Names
1 State/UT
2 Number of Households surveyed
3 Number of Women age 15-49 years interviewed
4 Number of Men age 15-54 years interviewed
5 Female population age 6 years and above who ever attended school (%)
6 Population below age 15 years (%)
7  Sex ratio of the total population (females per 1,000 males)
8 Sex ratio at birth for children born in the last five years (females per 1,000 males)
9 Children under age 5 years whose birth was registered with the civil authority (%)
10 Deaths in the last 3 years registered with the civil authority (%)
11 Population living in households with electricity (%)
12 Population living in households with an improved drinking-water source1 (%)
13 Population living in households that use an improved sanitation facility2 (%)
14 Households using clean fuel for cooking3 (%)
15 Households using iodized salt (%)
16 Households with any usual member covered under a health insurance/financing scheme (%)
17 Children age 5 years who attended pre-primary school during the school year 2019-20 (%)
18 Women (age 15-49) who are literate4 (%)
19 Women (age 15-49)  with 10 or more years of schooling (%)
20 Women age 20-24 years married before age 18 years (%)
21 Births in the 5 years preceding the survey that are third or higher order (%)
22 Women age 15-19 years who were already mothers or pregnant at the time of the survey (%)
23 Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%)
24 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any method6 (%)
25 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any modern method6 (%)
26 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Female sterilization (%)
27 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Male sterilization (%)
28 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - IUD/PPIUD (%)
29 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Pill (%)
30 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Condom (%)
31 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Injectables (%)
32 Total Unmet need for Family Planning (Currently Married Women Age 15-49  years)7 (%)
33 Unmet need for spacing (Currently Married Women Age 15-49  years)7 (%)
34 Health worker ever talked to female non-users about family planning (%)
35 Current users ever told about side effects of current method of family planning8 (%)
36 Mothers who had an antenatal check-up in the first trimester  (for last birth in the 5 years before the survey) (%)
37 Mothers who had at least 4 antenatal care visits  (for last birth in the 5 years before the survey) (%)
38 Mothers whose last birth was protected against neonatal tetanus (for last birth in the 5 years before the survey)9 (%)
39 Mothers who consumed iron folic acid for 100 days or more when they were pregnant (for last birth in the 5 years before the survey) (%)
40 Mothers who consumed iron folic acid for 180 days or more when they were pregnant (for last birth in the 5 years before the survey} (%)
41 Registered pregnancies for which the mother received a Mother and Child Protection (MCP) card (for last birth in the 5 years before the survey) (%)
42 Mothers who received postnatal care from a doctor/nurse/LHV/ANM/midwife/other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)
43 Average out-of-pocket expenditure per delivery in a public health facility (for last birth in the 5 years before the survey) (Rs.)
44 Children born at home who were taken to a health facility for a check-up within 24 hours of birth (for last birth in the 5 years before the survey} (%)
45 Children who received postnatal care from a doctor/nurse/LHV/ANM/midwife/ other health personnel within 2 days of delivery (for last birth in the 5 years before the survey) (%)
46 Institutional births (in the 5 years before the survey) (%)
47 Institutional births in public facility (in the 5 years before the survey) (%)
48 Home births that were conducted by skilled health personnel  (in the 5 years before the survey)10 (%)
49 Births attended by skilled health personnel (in the 5 years before the survey)10 (%)
50 Births delivered by caesarean section (in the 5 years before the survey) (%)
51 Births in a private health facility that were delivered by caesarean section (in the 5 years before the survey) (%)
52 Births in a public health facility that were delivered by caesarean section (in the 5 years before the survey) (%)
53 Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)
54 Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%)
55 Children age 12-23 months who have received BCG (%)
56 Children age 12-23 months who have received 3 doses of polio vaccine13 (%)
57 Children age 12-23 months who have received 3 doses of penta or DPT vaccine (%)
58 Children age 12-23 months who have received the first dose of measles-containing vaccine (MCV) (%)
59 Children age 24-35 months who have received a second dose of measles-containing vaccine (MCV) (%)
60 Children age 12-23 months who have received 3 doses of rotavirus vaccine14 (%)
61 Children age 12-23 months who have received 3 doses of penta or hepatitis B vaccine (%)
62 Children age 9-35 months who received a vitamin A dose in the last 6 months (%)
63 Children age 12-23 months who received most of their vaccinations in a public health facility (%)
64 Children age 12-23 months who received most of their vaccinations in a private health facility (%)
65 Prevalence of diarrhoea in the 2 weeks preceding the survey (Children under age 5 years) (%)
66 Children with diarrhoea in the 2 weeks preceding the survey who received oral rehydration salts (ORS) (Children under age 5 years) (%)
67 Children with diarrhoea in the 2 weeks preceding the survey who received zinc (Children under age 5 years) (%)
68 Children swith diarrhoea in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)
69 Children Prevalence of symptoms of acute respiratory infection (ARI) in the 2 weeks preceding the survey (Children under age 5 years) (%)
70 Children with fever or symptoms of ARI in the 2 weeks preceding the survey taken to a health facility or health provider (Children under age 5 years) (%)
71 Children under age 3 years breastfed within one hour of birth15 (%)
72 Children under age 6 months exclusively breastfed16 (%)
73 Children age 6-8 months receiving solid or semi-solid food and breastmilk16 (%)
74 Breastfeeding children age 6-23 months receiving an adequate diet16, 17  (%)
75 Non-breastfeeding children age 6-23 months receiving an adequate diet16, 17 (%)
76 Total children age 6-23 months receiving an adequate diet16, 17  (%)
77 Children under 5 years who are stunted (height-for-age)18 (%)
78 Children under 5 years who are wasted (weight-for-height)18 (%)
79 Children under 5 years who are severely wasted (weight-for-height)19 (%)
80 Children under 5 years who are underweight (weight-for-age)18 (%)
81 Children under 5 years who are overweight (weight-for-height)20 (%)
82 Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)
83 Women (age 15-49 years) who are overweight or obese (BMI ≥25.0 kg/m2)21 (%)
84 Women (age 15-49 years) who have high risk waist-to-hip ratio (≥0.85) (%)
85 Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)
86 Non-pregnant women age 15-49 years who are anaemic (<12.0 g/dl)22 (%)
87 Pregnant women age 15-49 years who are anaemic (<11.0 g/dl)22 (%)
88 All women age 15-49 years who are anaemic22 (%)
89 All women age 15-19 years who are anaemic22 (%)
90 Women  age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%)
91 Women age 15 years and above wih very high (>160 mg/dl) Blood sugar level23 (%)
92 Women age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level or taking medicine to control blood sugar level23 (%)
93 Men age 15 years and above wih high (141-160 mg/dl) Blood sugar level23 (%)
94 Men (age 15 years and above wih  very high (>160 mg/dl) Blood sugar level23 (%)
95 Men age 15 years and above wih high or very high (>140 mg/dl) Blood sugar level  or taking medicine to control blood sugar level23 (%)
96 Women age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)
97 Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)
98 Women age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)
99 Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)
100 Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)
101 Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)
102 Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)
103 Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)
104 Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)
105 Women age 15 years and above who use any kind of tobacco (%)
106 Men age 15 years and above who use any kind of tobacco (%)
107 Women age 15 years and above who consume alcohol (%)
108 Men age 15 years and above who consume alcohol (%)

In [26]:
df_selected= df.iloc[:,[0,1,7,11,12,14,19,20,24,25,26,27,28,29,30,31,46,53,54,76,77,80,82,85,88,90,97,102,103,104]]

In [27]:
df_selected.head()

,District Names,State/UT,"Sex ratio of the total population (females per 1,000 males)",Population living in households with electricity (%),Population living in households with an improved drinking-water source1 (%),Households using clean fuel for cooking3 (%),Women (age 15-49) with 10 or more years of schooling (%),Women age 20-24 years married before age 18 years (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any method6 (%),Current Use of Family Planning Methods (Currently Married Women Age 15-49 years) - Any modern method6 (%),...,Children under 5 years who are stunted (height-for-age)18 (%),Children under 5 years who are underweight (weight-for-age)18 (%),Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%),Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%),All women age 15-49 years who are anaemic22 (%),Women age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%),Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)
0,Nicobars,Andaman & Nicobar Islands,973,97.9,98.8,56.9,53.5,11.4,65.3,57.2,...,21.6,24.6,8.2,37.7,38.3,7.4,8.5,13.4,13.2,5.4
1,North & Middle Andaman,Andaman & Nicobar Islands,950,93.2,92.2,61.3,41.0,15.4,84.1,73.1,...,27.0,42.8,8.6,30.4,62.1,7.2,4.0,1.7,0.3,15.8
2,South Andaman,Andaman & Nicobar Islands,967,99.6,97.9,91.9,57.5,17.1,57.1,50.5,...,21.1,17.4,10.0,43.4,57.7,7.5,4.9,1.3,0.7,8.0
3,Srikakulam,Andhra Pradesh,1140,99.9,87.7,74.7,42.5,25.4,72.3,72.2,...,19.7,21.4,13.8,59.6,62.6,8.2,5.9,1.0,0.2,3.8
4,Vizianagaram,Andhra Pradesh,1114,99.5,93.1,60.3,37.6,33.7,71.2,71.2,...,36.4,32.2,16.9,66.7,64.0,6.2,6.6,4.9,0.6,7.3

In [29]:
for i,col in enumerate(df_selected.columns):
    print(i,col)

0 District Names
1 State/UT
2  Sex ratio of the total population (females per 1,000 males)
3 Population living in households with electricity (%)
4 Population living in households with an improved drinking-water source1 (%)
5 Households using clean fuel for cooking3 (%)
6 Women (age 15-49)  with 10 or more years of schooling (%)
7 Women age 20-24 years married before age 18 years (%)
8 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any method6 (%)
9 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Any modern method6 (%)
10 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Female sterilization (%)
11 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Male sterilization (%)
12 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - IUD/PPIUD (%)
13 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Pill (%)
14 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Condom (%)
15 Current Use of Family Planning Methods (Currently Married Women Age 15-49  years) - Injectables (%)
16 Institutional births (in the 5 years before the survey) (%)
17 Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)
18 Children age 12-23 months fully vaccinated based on information from vaccination card only12 (%)
19 Total children age 6-23 months receiving an adequate diet16, 17  (%)
20 Children under 5 years who are stunted (height-for-age)18 (%)
21 Children under 5 years who are underweight (weight-for-age)18 (%)
22 Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)
23 Children age 6-59 months who are anaemic (<11.0 g/dl)22 (%)
24 All women age 15-49 years who are anaemic22 (%)
25 Women  age 15 years and above with high (141-160 mg/dl) Blood sugar level23 (%)
26 Women age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)
27 Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)
28 Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)
29 Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)

In [30]:
final_cols = [0,1,2,3,4,5,6,7,16,17,19,20,21,22,23,24,27,28,29]

df_final = df_selected.iloc[:, final_cols]

df_final.shape

(706, 19)

In [31]:
df_final.columns = [
    "District",
    "State/UT",
    "Sex_Ratio",
    "Electricity",
    "Drinking_Water",
    "Clean_Fuel",
    "Women_Education",
    "Child_Marriage",
    "Institutional_Births",
    "Fully_Vaccinated_Child",
    "Adequate_Diet",
    "Stunted_Children",
    "Underweight_Children",
    "Women_Low_BMI",
    "Anaemic_Children",
    "Anaemic_Women",
    "Cervical_Screening",
    "Breast_Screening",
    "Oral_Screening"
]

In [33]:
df_final.head()

,District,State/UT,Sex_Ratio,Electricity,Drinking_Water,Clean_Fuel,Women_Education,Child_Marriage,Institutional_Births,Fully_Vaccinated_Child,Adequate_Diet,Stunted_Children,Underweight_Children,Women_Low_BMI,Anaemic_Children,Anaemic_Women,Cervical_Screening,Breast_Screening,Oral_Screening
0,Nicobars,Andaman & Nicobar Islands,973,97.9,98.8,56.9,53.5,11.4,97.8,(64.2),(18.7),21.6,24.6,8.2,37.7,38.3,13.4,13.2,5.4
1,North & Middle Andaman,Andaman & Nicobar Islands,950,93.2,92.2,61.3,41.0,15.4,97.7,*,(5.9),27.0,42.8,8.6,30.4,62.1,1.7,0.3,15.8
2,South Andaman,Andaman & Nicobar Islands,967,99.6,97.9,91.9,57.5,17.1,99.5,(76.3),23.5,21.1,17.4,10.0,43.4,57.7,1.3,0.7,8.0
3,Srikakulam,Andhra Pradesh,1140,99.9,87.7,74.7,42.5,25.4,97.9,(82.8),16.1,19.7,21.4,13.8,59.6,62.6,1.0,0.2,3.8
4,Vizianagaram,Andhra Pradesh,1114,99.5,93.1,60.3,37.6,33.7,99.0,(76.8),1.8,36.4,32.2,16.9,66.7,64.0,4.9,0.6,7.3

In [34]:
df_final.describe()

,Sex_Ratio,Electricity,Drinking_Water,Clean_Fuel,Women_Education,Institutional_Births,Women_Low_BMI,Anaemic_Women,Cervical_Screening,Breast_Screening,Oral_Screening
count,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000
mean,1020.640227,97.001700,93.722946,54.123088,40.326771,88.665014,17.894901,55.917280,1.574363,0.657649,0.705949
std,73.400047,4.354679,8.718210,24.181975,14.225720,12.007431,7.450438,11.946032,2.774812,1.569643,1.468871
min,755.000000,68.400000,41.200000,8.600000,13.600000,21.400000,1.200000,14.900000,0.000000,0.000000,0.000000
25%,969.000000,96.400000,92.000000,34.000000,29.300000,83.700000,12.700000,49.225000,0.200000,0.000000,0.000000
50%,1013.000000,98.700000,97.000000,50.500000,39.200000,92.200000,18.000000,57.200000,0.600000,0.200000,0.300000
75%,1065.750000,99.500000,99.300000,75.175000,49.875000,97.400000,23.100000,63.600000,1.500000,0.500000,0.700000
max,1332.000000,100.000000,100.000000,99.800000,88.200000,100.000000,43.600000,93.500000,23.200000,14.600000,15.800000

In [36]:
df_final.duplicated().sum()

np.int64(0)

In [37]:
df_final.isnull().sum()

District                  0
State/UT                  0
Sex_Ratio                 0
Electricity               0
Drinking_Water            0
Clean_Fuel                0
Women_Education           0
Child_Marriage            0
Institutional_Births      0
Fully_Vaccinated_Child    0
Adequate_Diet             0
Stunted_Children          0
Underweight_Children      0
Women_Low_BMI             0
Anaemic_Children          0
Anaemic_Women             0
Cervical_Screening        0
Breast_Screening          0
Oral_Screening            0
dtype: int64

In [65]:
df_final_st=df_final[["District","State/UT"]]
df_final_num=df_final.drop(columns=["District","State/UT"])

In [61]:
df_final_num

,District,State/UT,Sex_Ratio,Electricity,Drinking_Water,Clean_Fuel,Women_Education,Child_Marriage,Institutional_Births,Fully_Vaccinated_Child,Adequate_Diet,Stunted_Children,Underweight_Children,Women_Low_BMI,Anaemic_Children,Anaemic_Women,Cervical_Screening,Breast_Screening,Oral_Screening
0,,,973,97.9,98.8,56.9,53.5,,97.8,,,,,8.2,,38.3,13.4,13.2,5.4
2,,,967,99.6,97.9,91.9,57.5,,99.5,,,,,10.0,,57.7,1.3,0.7,8.0
3,,,1140,99.9,87.7,74.7,42.5,,97.9,,,,,13.8,,62.6,1.0,0.2,3.8
4,,,1114,99.5,93.1,60.3,37.6,,99.0,,,,,16.9,,64.0,4.9,0.6,7.3
5,,,1066,99.6,91.8,72.9,46.0,,95.3,,,,,17.4,,58.0,1.7,0.7,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,,,954,99.6,99.3,91.7,55.4,,97.5,,,,,6.6,,58.2,0.0,0.0,0.0
702,,,1055,99.2,100.0,36.2,34.9,,91.0,,,,,9.9,,61.6,0.0,0.0,0.2
703,,,1089,95.4,95.5,17.5,26.2,,87.6,,,,,18.9,,81.5,0.0,0.0,0.0
704,,,1031,99.0,87.8,17.0,30.9,,91.5,,,,,16.5,,70.4,0.0,0.2,0.5
705,,,977,97.0,95.2,56.3,37.1,,89.8,,,,,18.4,,65.8,0.7,1.3,0.4

In [41]:
df_final.isnull().sum()

District                  0
State/UT                  0
Sex_Ratio                 0
Electricity               0
Drinking_Water            0
Clean_Fuel                0
Women_Education           0
Child_Marriage            0
Institutional_Births      0
Fully_Vaccinated_Child    0
Adequate_Diet             0
Stunted_Children          0
Underweight_Children      0
Women_Low_BMI             0
Anaemic_Children          0
Anaemic_Women             0
Cervical_Screening        0
Breast_Screening          0
Oral_Screening            0
dtype: int64

In [42]:
df_final=df_final.replace('', np.nan)

In [43]:
df_final

,District,State/UT,Sex_Ratio,Electricity,Drinking_Water,Clean_Fuel,Women_Education,Child_Marriage,Institutional_Births,Fully_Vaccinated_Child,Adequate_Diet,Stunted_Children,Underweight_Children,Women_Low_BMI,Anaemic_Children,Anaemic_Women,Cervical_Screening,Breast_Screening,Oral_Screening
0,Nicobars,Andaman Nicobar Islands,973,97.9,98.8,56.9,53.5,114,97.8,642,187,216,246,8.2,377,38.3,13.4,13.2,5.4
1,North Middle Andaman,Andaman Nicobar Islands,950,93.2,92.2,61.3,41.0,154,97.7,NaN,59,270,428,8.6,304,62.1,1.7,0.3,15.8
2,South Andaman,Andaman Nicobar Islands,967,99.6,97.9,91.9,57.5,171,99.5,763,235,211,174,10.0,434,57.7,1.3,0.7,8.0
3,Srikakulam,Andhra Pradesh,1140,99.9,87.7,74.7,42.5,254,97.9,828,161,197,214,13.8,596,62.6,1.0,0.2,3.8
4,Vizianagaram,Andhra Pradesh,1114,99.5,93.1,60.3,37.6,337,99.0,768,18,364,322,16.9,667,64.0,4.9,0.6,7.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,Kolkata,West Bengal,954,99.6,99.3,91.7,55.4,167,97.5,802,316,296,329,6.6,723,58.2,0.0,0.0,0.0
702,South Twenty Four Pargana,West Bengal,1055,99.2,100.0,36.2,34.9,419,91.0,917,276,367,322,9.9,704,61.6,0.0,0.0,0.2
703,Paschim Medinipur,West Bengal,1089,95.4,95.5,17.5,26.2,557,87.6,769,218,311,400,18.9,660,81.5,0.0,0.0,0.0
704,Purba Medinipur,West Bengal,1031,99.0,87.8,17.0,30.9,576,91.5,884,209,258,306,16.5,675,70.4,0.0,0.2,0.5
705,Paschim Barddhaman,West Bengal,977,97.0,95.2,56.3,37.1,318,89.8,624,311,397,410,18.4,747,65.8,0.7,1.3,0.4

In [44]:
df_final.isnull().sum()

District                   0
State/UT                   0
Sex_Ratio                  0
Electricity                0
Drinking_Water             0
Clean_Fuel                 0
Women_Education            0
Child_Marriage             0
Institutional_Births       0
Fully_Vaccinated_Child    13
Adequate_Diet              1
Stunted_Children           0
Underweight_Children       0
Women_Low_BMI              0
Anaemic_Children           0
Anaemic_Women              0
Cervical_Screening         0
Breast_Screening           0
Oral_Screening             0
dtype: int64

In [52]:
df_final=df_final.dropna(subset=["Fully_Vaccinated_Child","Adequate_Diet"])

In [54]:
df_final.isna().sum().sum()

np.int64(0)

In [58]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 693 entries, 0 to 705
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   District                693 non-null    str
 1   State/UT                693 non-null    str
 2   Sex_Ratio               693 non-null    int64
 3   Electricity             693 non-null    float64
 4   Drinking_Water          693 non-null    float64
 5   Clean_Fuel              693 non-null    float64
 6   Women_Education         693 non-null    float64
 7   Child_Marriage          693 non-null    str
 8   Institutional_Births    693 non-null    float64
 9   Fully_Vaccinated_Child  693 non-null    str
 10  Adequate_Diet           693 non-null    str
 11  Stunted_Children        693 non-null    str
 12  Underweight_Children    693 non-null    str
 13  Women_Low_BMI           693 non-null    float64
 14  Anaemic_Children        693 non-null    str
 15  Anaemic_Women           693 non-null    float64
 16  Cervical_Screening      693 non-null    float64
 17  Breast_Screening        693 non-null    float64
 18  Oral_Screening          693 non-null    float64
dtypes: float64(10), int64(1), str(8)
memory usage: 137.8 KB

In [ ]:
df